name: poDTest Action
description: Run poDTest to build, test, and clean up a Docker container
author: h4nz0x
branding:
  icon: activity
  color: yellow
inputs:
  dockerfile-path:
    description: Path to the Dockerfile
    required: false
    default: ./deployments/Dockerfile
  port:
    description: Internal port to expose
    required: false
    default: "8000"
  health-check-path:
    description: Health check endpoint path
    required: false
    default: /health
  health-check-timeout:
    description: Timeout for health check in seconds
    required: false
    default: "10"
  health-check-interval:
    description: Number of health check attempts
    required: false
    default: "5"
  build-timeout:
    description: Timeout for image build in seconds
    required: false
    default: "300"
  hot-fix:
    description: Enable hot-fix mode (true/false)
    required: false
    default: ""
runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
    INPUT_PORT: ${{ inputs.port }}
    INPUT_HEALTH_CHECK_PATH: ${{ inputs.health-check-path }}
    INPUT_HEALTH_CHECK_TIMEOUT: ${{ inputs.health-check-timeout }}
    INPUT_HEALTH_CHECK_INTERVAL: ${{ inputs.health-check-interval }}
    INPUT_BUILD_TIMEOUT: ${{ inputs.build-timeout }}
    INPUT_HOT_FIX: ${{ inputs.hot-fix }}
  entrypoint: /entrypoint.sh